# DATA
model: pspnet101
data: &data cityscapes
name: &name cityscapes_pspnet101_weight
train_path: !join ['temp', *data, 'train.txt']
val_path: !join ['temp', *data, 'val.txt']
label_op: mapping
label_list: [7, 8, 11, 12, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33]
num_classes: 19
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
  
# TRAIN
layers: 101
train_h: 713
train_w: 713
scale_min: 0.5  # minimum random scale
scale_max: 2.0  # maximum random scale
rotate_min: -10  # minimum random rotate
rotate_max: 10  # maximum random rotate
zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
ignore_label: 255
aux_weight: 0.4
num_workers: 8  # data loader workers
batch_size: 2  # batch size for training
batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
base_lr: 0.01
max_epochs: 200
power: 0.9
momentum: 0.9
weight_decay: 0.0001
print_freq: 200
ckpt_dir: &ckpt_dir !join ['checkpoints', *name]
ckpt_latest_path: !join [*ckpt_dir, 'latest_model.pth']
ckpt_best_path: !join [*ckpt_dir, 'best_model.pth']
log_dir: !join ['logs', *name]
weight:  # path to initial weight (default: none)

weight_dir: !join ['temp', *data]

# TEST:
test_path: !join ['temp', *data, 'val.txt']
base_size: 512  # based size for scaling
test_h: 473
test_w: 473
scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
colors_path: !join ['temp', *data, 'colors.txt']
names_path: !join ['temp', *data, 'names.txt']
save_dir: !join ['results', *name]